### ISSUE TITLE
Can a new release be created?

### ISSUE THREAD

**Issue by denisse-dev** [CyberShadow/znc-clientbuffer#7]
Hello, thank you so much for actively maintaining this package.
I wanted to know if it's possible for you to create a new release for `znc-clientbuffer`? This is because the only release is from 5 years ago.

Thanks in advance.

**Comment by CyberShadow** [comment]
Sorry, do you mean, a git tag?

I'm not even sure what the sole existing git tag is for. It doesn't look like a release or version number for this project.

I could make a tag, though, it would help to know what this will solve, and how often it would be useful to continue doing so.

**Comment by denisse-dev** [comment]
Sorry for taking so long to reply.

Yes a Git tag using semantic versioning could be useful in case it's not much hassle, the reason why that would be useful is to be able to select an specific version of `znc-clientbuffer` and be able to cryptographically validate the integrity of the package using its hash, [proxychains-ng](https://github.com/rofl0r/proxychains-ng/releases) does this and it makes it pretty easy to automate the process when installing this using a provisioner and it also allows to use a stable version of the program.

What do you think?

**Comment by BtbN** [comment]
Keep in mind that the hash of tarballs github creates for commits and tags can change any time, since they are dynamically created and a new tar version can change the hash of the archive.
Git git commit hash itself is a much better hash to check against.

**Comment by CyberShadow** [comment]
Created tag v1.0.44. (Semantic version compatible, with the last number indicating the number of commits in the repository so far.) Now I just have to remember to do that periodically, I guess.

> and be able to cryptographically validate the integrity of the package using its hash

I think a tag does not provide any additional guarantees in this regard over a commit hash. Even though SHA-1 commit hashes are susceptible to SHA-1's vulnerabilities, one would need to have write access to this repository to exploit them, at which point they could just move the tag. Due to current complexity of creating a SHA-1 collision, a commit hash actually seems better than a tag in this regard.

> a new tar version can change the hash of the archive

This seems unlikely to me, as GitHub almost certainly uses an implementation for serializing repositories to archives that's under their control.

**Comment by BtbN** [comment]
Gentoo had a lot of issues with that, where packages referenced the automatically created tarballs for commits/tags, and after a couple months all hash verification suddenly failed, since GitHub updated their tar version.
So they are not cached indefinitely and cannot be relied upon to never change their hash under normal conditions.

**Comment by denisse-dev** [comment]
I haven't thought about using the commit hash for this, it's a good idea too!

I didn't knew about the problem Gentoo had, it's pretty interesting!

Thanks for creating the new release! :)

**Comment by BtbN** [comment]
What I've been doing on a few projects is just downloading the GitHub-Generated tarball of the release, and then re-uploaded it unmodified as artifact for that release. The hash of that is for sure never going to change.
